### ISSUE TITLE
Standard tie-breaking practice

### ISSUE THREAD

**Issue by MatthewMiddlehurst** [uea-machine-learning/tsml#110]
Based on a small discussion we had in the office, do we have a standard practice for tie-breaking? Do all classifiers use the same method and what method should be used? i.e. first item, random selection, weighted random selection using class distribution.
Mostly in the context of class selection for classification but could be extended to other situations with ties.
Mainly for discussion, if this is a non-issue feel free to close.

**Comment by James-Large** [comment]
Not to hijack, but this could also be included in something like the AbstractClassifierWithTrainingData or whatever it was called, or really any extra base class type for our classifiers beyond AbstractClassifier

e.g breakTies, setSeed etc

**Comment by TonyBagnall** [comment]
are we talking about ties in classifyInstance, for when best probabilities are equal? Could generalize that, but not sure about the best syntax. We also might want a static method for a call from experiments say to avoid calling distributionForInstance and classifyInstance?

**Comment by MatthewMiddlehurst** [comment]
Yeah, mainly for probabilities in classifyInstance. No current standard way to resolve ties or consensus if it really matters what way it happens.

**Comment by TonyBagnall** [comment]
in the absence of any further info, ties should be settled randomly.

**Comment by TonyBagnall** [comment]
so an method and a static method in AbstractClassifierWithTrainingData would be appropriate. Could be 

//Return index of the largest value, with ties settled randomly
double findBest(double[] x){}
better than two stage: find best, if tie, resolve tie?

**Comment by MatthewMiddlehurst** [comment]
Would be better, i think most classifiers use indexOfMax in Utilities which returns the first item in any ties

**Comment by TonyBagnall** [comment]
bumping this as I'm working on the abstract base. So a default method (and static method) int findIndexOfMax(double[] x) with ties settled randomly yes?

**Comment by James-Large** [comment]
This needs to be standardised and yeah I think just settle randomly (seeded if the classifier itself is seeded), but just a small warning that this will result in (insig) differences to some old results.

**Comment by TonyBagnall** [comment]
I'm bumping this, if not one wants to do it, and if we get GSoC students, this would be a good first issue

**Comment by TonyBagnall** [comment]
completed by Multivin12, I'll leave this open until classifiers are updated to actually use it, that may cause some disruption with reported results etc
