### ISSUE TITLE
redesign of HiveCote classifier

### ISSUE THREAD

**Issue by TonyBagnall** [uea-machine-learning/tsml#116]
this needs updating. Desired characteristics:
1. Use ClassifierResults not bespoke file writing
2. Mechanism for checking if results are present, then build from file
3. Ability to thread the components
4. Contractable and Checkpointable, just by using Contractable and Checkpointable components. 

volunteers?

**Comment by MatthewMiddlehurst** [comment]
Assume we would still need contract EE and TSF (is there already a contract version?), but i don't mind setting some of the ground work. Sounds similar to a lot of the stuff i have done in BOSS.

**Comment by TonyBagnall** [comment]
nice one. Contract EE is on its way I think, just needs a timer rather than percentages. TSF is not contracted yet, but it is very easy to do so, just add a timer check in the build loop.

**Comment by James-Large** [comment]
A couple of ways to go with this, but we could separate out the 'generic ensemble classifier' code from cawpe (which is the majority of it minus the specific base classifier/weighting/voting schemes) and have that as a base (abstract?) ensemble class, of which e.g. hive-cote, cawpe, ensembleselection, etc are simply named versions/subtypes

The base ensemble could then have options for threading, contracting and checkpointing too. 

Would turn it into a bit of a god-class, implementing multiple potentially ill-defined interfaces, but each individually would be fine

* Could have options to read base classifier results from file, in which case all below interface options turn off. 
* Could be contractable, where it will by default give equal time to each member if all members implement the contractable interface (for training, I'll assume here). If not all classifiers implement contractable, either fail or try to train the non-contractable ones first
* Could be threadable, where given a number of threads it is allowed to use (default min(numCores, numBaseClassifiers), it will give one to each base classifier, and then any remaining threads will be spread among base classifiers that are themselves threadable
* Could be checkpointable, where each base classifier shall be trained in turn, performing any checkpointing they themselves can do, but then the ensemble also performing it's own checkpointing after each baseclassifier is trained.

Combinations of the above could be ok... but it would likely all get messy (especially in the API) in combination with the perceived option of ensembling from file

So potentially the alternative is the separate out post-processing ensembles from file, and building ensembles in memory into separate classes

**Comment by TonyBagnall** [comment]
so I think a generic ensemble is the way to go, but we should do this incrementally to see how it all fits together. Perhaps we have a vanilla one, then restructure CAWPE and HIVE-COTE to use it first. We may then either enhance or subtype the vanilla one with above options. But first I'd like to get everything working and examples of it for potential bakeoff recreation. Then the workflow is

**Comment by James-Large** [comment]
PR #130 implemented a potential [hivecote](https://github.com/uea-machine-learning/uea-tsc/blob/dev/src/main/java/weka_uea/classifiers/ensembles/HIVE_COTE.java) as an extension of a generic ensemble. Basic threading of one-per-baseclassifier implemented and tested via CAWPE, though more thorough testing is always good, and equivalent contracting functionality/assumptions about base classifiers as is in the existing bespoke HiveCote brought over. Checkpointing todo, exact classifier settings/setup to be confirmed etc

**Comment by TonyBagnall** [comment]
I've used the new design and I'm happy with HIVE-COTE, I will refactor it into the right place and depreciate the old one.
