### ISSUE TITLE
distance measures

### ISSUE THREAD

**Issue by TonyBagnall** [uea-machine-learning/tsml#118]
we currently have two packages for distance functions:
timeseriesweka.elastic_distance_measures and
timeseriesweka.filters.shapelet_transforms.distance_functions
it would be nice to tidy this up somehow. Any thoughts? We also have the wrapped FastWWS with its own package structure. 

distances are not classifier only, so I think a single package is good. Weka puts them in core, but I dont like that. I think just a package distances? Maybe subpackage elastic_distance and window_distance? And then, do we continue to implement weka DistanceFunction?

**Comment by ABostrom** [comment]
I like the idea of sub packages elastic and window. 

What would you want the API to look for a base distance function, and for elastic and windowing. 

stick with 1D double arrays? Do we want to support multi-dimension. Everything is a 2D array? but univariate is just [1][length] ?
