### ISSUE TITLE
Gradle configuration still set to old name

### ISSUE THREAD

**Issue by goastler** [uea-machine-learning/tsml#132]
Gradle config is still set to old name "uea-tsc" so is very confusing when opened in an IDE supporting gradle!

**Comment by TonyBagnall** [comment]
hi george, this is still the case, is it easy to fix? 

![image](https://user-images.githubusercontent.com/9594042/66231503-92b56380-e6de-11e9-9631-4d7b3456d637.png)

**Comment by TonyBagnall** [comment]
will close this too and just live with it :)
