### ISSUE TITLE
TrainAccuracyEstimator interface

### ISSUE THREAD

**Issue by TonyBagnall** [uea-machine-learning/tsml#135]
so almost certainly originating with me, some classifiers implement this interface but all they do is a CV. This is high maintenance when the Experiments could do it anyway. So I think unless it has the capacity to do something other than CV, it should not implement this interface. 

For those that do, I think we should split the time to estimate error and the final build time in ClassifierResults, and store them both.

thoughts?

**Comment by James-Large** [comment]
There's a field in classifier results for setting estimate time and method, came in with evaluator updates (just as a loosely defined string for now, e.g. cv_10, not tied down yet). 

Doing experiments with a few different classifiers recently, especially where I want accurate times to evaluate different intervals, and yeah I'm liking TrainAccuracyEstimator less and less 

I cant really remember if this was precise intention of it _originally_, but what I've fallen into is expecting/wanting it to be is 'this classifier estimates it's own performance as part of its natural build process'. In that case, estimate time sort of equals build time. 

Currently, it seems like that's true for some classifiers, others estimate accuracy more efficiently than nested cv but it's still an extra step outside normal building (e.g. boss I think), others just make a cv object and call that (e.g. tsf, if not bagging). Makes it difficult to figure out what should be used between build time and estimate time.

Say for cawpe, the process of generating an estimate is:
   - cross validating the base classifiers (natural part of build process)
   - combining the aligned predictions as a post-process step (very cheap, almost negligible, but an extra step)

Should the estimate time be the second step only, or both? Does it matter that the first step is already accounted for in build time? etc 

For non-train acc estimators, I know that the estimate time is completely separate - the build time is measuring buildclassifier on the train set, estimate time is measuring 10foldcv(or whatever) on the train set. 

Again, mainly questions between technical truth in theoretically separated experiments, versus practicalities of skipping steps in runtime

Maybe you have three fields lol, isolated build time, isolated estimate time, and 'in practice build plus estimate time'. Then when analysing timings afterwards you look at whichever's important for the use case. For non-trainaccestimators, experiments just adds the two together to form the third, but maybe trainaccestimators are selective about parts of the build/estimate process to add to each field

**Comment by TonyBagnall** [comment]
so on timings, I think we should split int trainEstimateTime (a) and buildTime (a)  and store totalTime (a+b). If it is a TrainAccuracyEstimator, it has to store both of these in buildClassifier if train estimates are found, otherwise trainEstimateTime =0. If not, then Experiments records time, if it is performed.

the second question, which touches on the first, is how much of this to delegate to the classifiers, and how much to externally model. This comes down to how much we can generalise strategies. As I see it, there are 

1. Estimate with CV: Proximity Forest, WEASEL? Issue here is folds and number of cases to use. Basic assumption is we will always fit the final model on all, so trainEstimateTime >0
2. Estimate by bagging (if possible): RISE, TSF, STC. Issue here is whether to do in the buildTime (i.e. single bagged classifier), so estimateTime=0, or do separate, when estimateTime>0
3. Estimate through the tuning process (e.g. take the value of the best found parameters): BOSS, EE
estimateTime=0, since it is a biproduct of the buildClassifier
4. Estimate with a proxy. We have not done this as yet

I'm sure strategies exist, cant think of any right now though. It can also all be wrapped in Bayesian framework for our priors on the estimate, which would give us a distribution and would then possibly improve usage by hive-cote, but this is further down the path.

**Comment by TonyBagnall** [comment]
so can I suggest that for now, we just explicitly record the different time scenarios, and we then leave the redesign for now? For contracting, we assume the contract is for the buildTime only for now. Again, can reconsider later. So for hive cote components
TSF: CV or Bagging
RISE: CV or Bagging
BOSS: Search
EE: Search
ST: either full CV, transform +CV or transform + Bagging

I'm intending to evaluate the effect of these settings in the medium future

**Comment by TonyBagnall** [comment]
closing this as I seem t have taken it off topic! TranAccEst is no more
