### ISSUE TITLE
Branch protection

### ISSUE THREAD

**Issue by goastler** [uea-machine-learning/tsml#137]
We need some form of branch protection for the dev branch. @MatthewMiddlehurst accidentally deleted the dev branch earlier this week and managed to recover it (phew!). To prevent this from happening again, we need some kind of protection over the important branches. Master is already protected.

On github, to protect a branch you have to make a branch protection rule. I made a rule for master which is why you can't push directly to it. We have two options for dev:

1. make an empty rule which stops accidental deletion / renaming / etc
2. protect dev in the same way as master, preventing pushing unless via pull request. This is a popular option to maintain a clean dev version, but comes at the cost / pain of having to do pull requests every time (although I think it's a good idea)

We at the very least need option 1, would like some feedback on option 2 :)

**Comment by TonyBagnall** [comment]
yes I agree, I have been working directly off dev and the above explains some weirdness I've seen. I think we just go (2) and I stop working directly in dev! But if travis checks pass, we should be able to merge our own pull requests.

**Comment by TonyBagnall** [comment]
George, can you sort this out? ta

**Comment by James-Large** [comment]
I think 2, but hat's been my workflow anyway so no change for me

**Comment by ABostrom** [comment]
I think 2 as well.

If we all have our own sub-devs. (aaron-dev/ tony-dev etc) then PR the bits we want into dev as we go it will be much safer imo.

**Comment by TonyBagnall** [comment]
yes 2 with travis checks but with no approval required other than passing checks

**Comment by goastler** [comment]
Great, I'm happy with option 2 also :)

However, I'm not an admin on the repo so I think only @TonyBagnall can sort it out (sorry!). If you let me know when you're next free Tony I can drop by and apply the branch protection with you :)

**Comment by goastler** [comment]
Also yes, no review necessary so we can merge our own PRs

**Comment by TonyBagnall** [comment]
can we do this next weds? Thats when Im next in

**Comment by goastler** [comment]
Sorted
