### ISSUE TITLE
Master-Compile errors package statistics.transformations

### ISSUE THREAD

**Issue by davcem** [uea-machine-learning/tsml#150]
I checked out the master (ef5fd1056a4a66f81c41f9fee8ca22e1ef22a866) yesterday and noticed compile problems since the package specification for all files in statistics.transformations is: package transformations instead of package statistics.transformations;
src/main/java/statistics/tests/ResidualTests.java also imported transformation package

**Comment by TonyBagnall** [comment]
hi, thanks for that, we had another weird package problem that I thought travis would have picked up on. I will look now.

**Comment by TonyBagnall** [comment]
this is really odd, none of it showing up as errors in the ide, but sure enough it is in the wrong place. thanks for spotting this, I will refactor it. Some strange netbeans thing, speed the shift to intellij

![image](https://user-images.githubusercontent.com/9594042/65046079-d62a7680-d957-11e9-8d30-27258981af33.png)

**Comment by davcem** [comment]
Never mind, I am almost constantly dealing with these kind of shenanigans with Eclipse... :-)

**Comment by TonyBagnall** [comment]
we are moving to intellij soon. I'll post here when its fixed, this code is from 2006, the double indentation is from when I switched from eclipse to netbeans!

**Comment by davcem** [comment]
Oh okay, that is already a while ago. Thank you!

**Comment by TonyBagnall** [comment]
think this is fixed, could you try it now?

**Comment by davcem** [comment]
Looks good 
![2019-09-17-16-04-34-Screener-uea](https://user-images.githubusercontent.com/12966595/65048799-fdd40b80-d964-11e9-8d07-aa6b5d7d85be.png)
