### ISSUE TITLE
FlatCote.main() results in java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by davcem** [uea-machine-learning/tsml#151]
Execution of timeseriesweka.classifiers.hybrids.FlatCote.main() in master (ef5fd1056a4a66f81c41f9fee8ca22e1ef22a866) produces an exception with the following details:

Exception in thread "main" java.lang.IllegalArgumentException: Src and Dest differ in # of attributes: 68 != 1
	at weka.core.RelationalLocator.copyRelationalValues(RelationalLocator.java:87)
	at weka.filters.Filter.copyValues(Filter.java:371)
	at weka.filters.Filter.push(Filter.java:288)
	at weka.filters.SimpleBatchFilter.batchFinished(SimpleBatchFilter.java:257)
	at weka.filters.Filter.useFilter(Filter.java:682)
	at weka_extras.classifiers.ensembles.AbstractEnsemble.buildClassifier(AbstractEnsemble.java:890)
	at timeseriesweka.classifiers.hybrids.FlatCote.buildClassifier(FlatCote.java:104)
	at timeseriesweka.classifiers.hybrids.FlatCote.main(FlatCote.java:185)

Problem is caused by applying filter ShapeletTransform in weka_extras.classifiers.ensembles.AbstractEnsemble.buildClassifier(AbstractEnsemble.java:890) --> It seems that the usage of Filter causes the problem for ShapeletTransform. 

If I call the ShapeletTransform.process(data) directly the exception is not thrown, tested via change of AbstractEnsemble:
Line 888 else{
           transform.setInputFormat(data);
           this.trainInsts = Filter.useFilter(data,transform);
        }
into: 
Line 888 else{//changed by davcem: There is some filter issue when using 
        	if(this.transform instanceof ShapeletTransform){
            	this.trainInsts = ((ShapeletTransform)transform).process(data);
        	}else{
        		transform.setInputFormat(data);
                this.trainInsts = Filter.useFilter(data,transform);	
        	}
        }

This is just a quick hack, but I think that the "new way" of useFilter cases issues with the ShapeletTransform Filter.

**Comment by TonyBagnall** [comment]
good spot, I'll take a look, cheers!

**Comment by TonyBagnall** [comment]
I've assigned James to this, this is his class so I dont want to meddle :)

**Comment by davcem** [comment]
You are welcome, this seems tricky (at least for someone not creating/maintaining ShapeletTransform), let me know if I can test something ;-)

**Comment by davcem** [comment]
The exception is caused each time the transformer is used for filtering in AbstractEnsemble:
* Function distributionForInstance(), Line 969
* Function classifyInstanceByConstituents(), Line 1024
* Function distributionForInstanceByConstituents(), Line 1045

**Comment by TonyBagnall** [comment]
it looks like ShapeletTransform is not set up to use filters correctly, we have tended to abuse Filter by calling process directly, because the default way is horribly clunky. I think I can sort that. As an aside, FlatCote is really only there for legacy, we use HiveCote as it is better

**Comment by davcem** [comment]
Yeah I thought about that, but for the paper I am working on I want to use the best classifiers for the singleTrainTest and unfortunately for the two Class datasets Flat-COTE is better performing than HIVE-Cote. Nevertheless I tried to integrate HIVE-Cote into my code, tested it but it results in an exception, for which I openend another issue #153  :-)

**Comment by TonyBagnall** [comment]
FlatCote should work as advertised now, I'll close this, please raise a new issue if you encounter further problems.
