### ISSUE TITLE
timeseriesweka.filters.shapelet_transforms

### ISSUE THREAD

**Issue by TonyBagnall** [uea-machine-learning/tsml#16]
yikes! I will have a little tidy up (GraceShapeletTransform) but I think this needs a bottom up reconstruction. Perhaps do the python version first. I think James has a start on the slimmed down version? 
![image](https://user-images.githubusercontent.com/9594042/52332527-cbd3f180-29f2-11e9-8e18-4e9ac41d5cba.png)

**Comment by James-Large** [comment]
I only did a very quick/very minimal/very minimally tested 2d shapelets version for the bags project, I think just ignore that

**Comment by ABostrom** [comment]
I think we need to define what we want shapelets to be able to do. 

Do we want to be able to find shapelets. construct transforms from them. construct trees from them?

Support the different distance measures, and quality measures etc.

**Comment by TonyBagnall** [comment]
So the core functionality of the shapelet_transform is to search the *data* for shapelets. Lets just get that a bit tidied up first. Can any of the above be removed (e.g GraceShapeletOptions and ApproximateShapeletTransform) and can any others be nested? e.g. Do we need to see Shapelet and ShapeletCandidate? I'll remove ShapeletTransformLight. I would like a single filter class in the directory filters. The rest can stay in its own directory, but do we really need a package class_value, and if we do, could it not move to utilities? Oh and: comment your code!

**Comment by ABostrom** [comment]
The general structure of the subapackages is: there are two different types of class values, but they share a common interface. This could go into utilities. A classifier shouldn't necessarily need to know whether it is using a binary or regular encoding. so it's wrapped up.

distance/quality/search functions are self explanatory subpackages. 

Distance measures are bespoke implementations for ST. Quality measures are bespoke to ST also.
I believe both of these could be majorly tidied up, and be more general purpose implementations. 

SearchFunctions atm are bespoke to searching for shapelets, these are used with ST. but could just as readily be used in a forest or tree implementation. if we wanted to. Could build contract random shapelet forest very simply.

**Comment by TonyBagnall** [comment]
so please refactor/tidy/comment when and if you get a chance, but push regularly as I am also background working with shapelets for the STC, so dont want to get out of sync.

**Comment by TonyBagnall** [comment]
in fact I just refactored ShapeletTransformLight, so will push it now!

**Comment by ABostrom** [comment]
Yeah. I'll put it on my list.

**Comment by TonyBagnall** [comment]
I've done/am doing this, so will close the issue
