### ISSUE TITLE
ShapeletTransformClassifier train fold bug

### ISSUE THREAD

**Issue by MatthewMiddlehurst** [uea-machine-learning/tsml#160]
ShapeletTransformClassifiers train files generated by Experiments currently only have usable results for the first cross validation fold. Subsequent folds only output probabilities of 0 for all classes. As James noted this is most likely due to buildClassifier being called multiple times during the Experiments CV, with calls past the first retaining information and somehow breaking.

STC should either be changed to fully reset upon subsequent calls of buildClassifier, or be made a TrainAccuracyEstimator to create its own results (or both).

**Comment by TonyBagnall** [comment]
I've looked at the code and as far as I can tell it resets each time. I run this on Chinatown and I get this output in the train 
![image](https://user-images.githubusercontent.com/9594042/66082620-6bd22280-e562-11e9-8be3-dce6ca89eff3.png)

and this on test
![image](https://user-images.githubusercontent.com/9594042/66082599-607ef700-e562-11e9-9cd3-b21d195ddf10.png)

I assume the cvfold etc is meant to be there.

**Comment by James-Large** [comment]
@MatthewMiddlehurst what exact classifier setup did you use, or setclassifier key etc?

**Comment by MatthewMiddlehurst** [comment]
The setClassifier key is 'ST' which runs a 5 hour contract for STC. Currently rerunning the same config after pulling dev, this may just be a weird conflict on my end.

**Comment by TonyBagnall** [comment]
send me the data I'll try reproduce your error

**Comment by MatthewMiddlehurst** [comment]
New folds created after pulling an updated STC/Experiments no longer have any issue. I am currently assuming it was an old version of STC interacting poorly with the multiple buildClassifier calls from Experiments CV as James suggested.

**Comment by TonyBagnall** [comment]
ok, can we close this issue?

**Comment by MatthewMiddlehurst** [comment]
Yeah sounds good. Left it up in-case anyone wanted to make a comment about general error checking/results validation as this seems like something that could possibly re-occur later down the line, but a new issue can be created if that's something we wish to look into.
