### ISSUE TITLE
Checkpoint specifics

### ISSUE THREAD

**Issue by MJFlynn** [uea-machine-learning/tsml#171]
So broadly the question is, how/when should the classifier attempt to load from file?

The obvious option would be to include this at the begining of buildClassifier (see TSF). However, perhaps there is an argument to include specific methods in the checkpointing interface allowing more control? Personally, I'd be happy managing it either way

But, I do think we should include a built Boolean in the interface to account for cases in which a hard limit is hit during testing.

Lastly, any opinions on a naming convention?

**Comment by TonyBagnall** [comment]
dumping this. So currently I believe checkpointing is either turned on or off the ExperimentalArguments
![image](https://user-images.githubusercontent.com/9594042/76391520-97ee9c80-6367-11ea-9e65-6ba7190fdf58.png)
would it be better to be able to pass it a checkpoint time, as with contract e.g. "-cprh=3"

**Comment by James-Large** [comment]
Could do, e.g. -cprh --checkpointRateHours = how frequently the classifier should try to checkpoint? And maybe an option for minutes etc. 

Similar mentioned in #281, but I don't in general like the idea of multiple flags for the same thing, just in different units. Some solution of the value having a suffix s,m,h,d for the time unit could be easy depending on any weird/wacky ways people by be automating their script generation

From pov of experiments this should all be fine, obviously up to the classifiers to make use of the flags

Would this replace the current boolean behaviour with the classifier choosing when to checkpoint?

**Comment by TonyBagnall** [comment]
yeah thats fine, so lets just checkpoint in hours. i think maybe just replace the boolean? what do others who have implemented it think?

**Comment by TonyBagnall** [comment]
my opinion is that checkpointing is very much an experimental feature, so setting it by experiments makes sense. we could keep the boolean for default settings and another for setting hours?

**Comment by TonyBagnall** [comment]
so the default way of controlling checkpointing is by these variables which can be set through experiments with the argument -cp. If checkpointing is true and no time is set, the algorityhm decides on the interval between checkpoints 
![image](https://user-images.githubusercontent.com/9594042/79001177-ebf6c780-7b45-11ea-8765-f8d8c948f381.png)
