### ISSUE TITLE
What timings to measure

### ISSUE THREAD

**Issue by James-Large** [uea-machine-learning/tsml#172]
I've tried to formalise what I think the situation should be in terms of things we should time. Give feedback, criticise etc. This is important because everyone will be expected to adds these into their respective classifiers, and these are the timings that will be available to you when you come to analyse your own results for comparisons between classifiers. If you want more, say so. For a particular classifier that wants to measure things for its own internal reasons, that's fine, that can go on the second/para line. But for comparison between classifiers, stuff needs to be mutually agreed. 

There are a few factors here: we want to store consistent, complete-for-our-needs but minimal information in ClassifierResults objects and files. We have things that we want to measure for to use in later experiments/classifiers, and we have things that we want to measure for human interpretation of results. 

Below's a doc explaining the standard timings that I think we should keep in all classifiers that extend EnhancedAbstractClassifier, and experiments will measure them for classifier that do not (the timings are straightforward for those anyway). The exact names are not set in stone. It's the ideas that are important. The idea would likely be that all the timings that the classifier measure themselves will have get/set methods in ClassifierResults, while those timings that are automatically calculated could only have get methods. Debatable

Additional to these, there's the option of recording 'experimentalTime', e.g. time to write/load checkpoints and so on. Then we'd have the option of doing fullBuildTime - experimentalTime time, etc. 

[timings problems.pdf](https://github.com/uea-machine-learning/tsml/files/3724131/timings.problems.pdf)

**Comment by TonyBagnall** [comment]
I think we have settled this, I'll close now. We can always reopen later
