### ISSUE TITLE
This shapelet is strange, help me interprat it, please !

### ISSUE THREAD

**Issue by frankl1** [uea-machine-learning/tsml#177]
Hi,

I'm trying to analyse the shapelets that have been extracted from the [Chinatown](http://www.timeseriesclassification.com/description.php?Dataset=Chinatown) dataset. To do so, I used the following step.

1. Train ST on the dataset to extract the shapelets; here is the code snippet
```
                ShapeletTransform transform = new ShapeletTransform();
		transform.setClassValue(new BinaryClassValue());  
		transform.setSubSeqDistance(new SubSeqDistance());  
		transform.setShapeletMinAndMax(min, max);
		transform.setLengthIncrement(lenghtIncrement);
		transform.useCandidatePruning();
		transform.setNumberOfShapelets(train.numInstances() * 10);
		transform.setQualityMeasure(ShapeletQualityChoice.INFORMATION_GAIN);
		transform.setLogOutputFile(shapeletFile);
		transform.supressOutput();
```

2. Since shapelets are zNormalized, I try to recover the original values of each shapelet _shp_ as follow
`x = y * std(shp) + mean(shp) `.
this formula is applied on each value y of the considered shapelet _shp_

3. Then I plot the recovered shapelet and its corresponding time series on the same axes
![Strange - Shapelet - Chinatown](https://user-images.githubusercontent.com/23366578/66842642-e429e200-ef6b-11e9-8c69-0bbcd09e67bc.png)

As you can see on the plot, the shapelet deviates too much from the original series and that is why it is very strange. Shapelets are supposed to be subsequences of a time series in the dataset.

I'm wondering if it is not due to floating point number computation, or a mistake in my process, or something else.

Thanks

**Comment by TonyBagnall** [comment]
hi, the shapelet log includes the series index and position of the original series, you can just take if from the data. To reverse the normalisation you would need the original mean and std dev. Alternatively, I think there is now the facility to turn off normalisation. I'll ask @ABostrom

**Comment by frankl1** [comment]
Yes, you're right
Actually I used the series index and the starting position of the shapelet to retrieve the original shapelet (before normalization). Then I computed the original mean and standard deviation. Finally I used the computed mean and std to reverse the normalization. Below is a python snippet for that
```
def recover(shapelet, dataset):
    ts = dataset.loc[shapelet.series_id]
    origin = ts[shapelet.start_pos : shapelet.start_pos + len(shapelet.content)]
    mean = origin.mean()
    std = origin.std()
    return [x*std + mean for x in shapelet.content]
```

It's true that I can simply extract the shapelet using the series index and the position, but what I actually want is to view the shapelet that is used during the testing phase.

**Comment by ABostrom** [comment]
All shapelets are Z-normalised. 

Your python code does not z-norm.

In python you should do:
`return [(x-mean)/std for x in shapelet.content]`

**Comment by frankl1** [comment]
Yes I agree, but actualy I want to reverse normalization so the shapelet will line up with its original series

**Comment by ABostrom** [comment]
Yeah. The problem is with that method, you can't get the original standard deviation, and mean of the original shapelet without just retracting it. At which point you could just plot it.

Z-Normalisation cannot be undone, if you only have the normalised shapelet. Hence why we publish the lengths and positions and series id

**Comment by TonyBagnall** [comment]
could you post the whole shapelet log here please? I'll take a look then

**Comment by TonyBagnall** [comment]
So I have just run chinatown and recreated the extracted shapelets. Two things: indexing is from zero, are you looking at the correct series, and are you using sktime not tsml? The shapelet you give above is from series 7 position 20
![image](https://user-images.githubusercontent.com/9594042/67203759-dd83ea80-f403-11e9-8d49-f5acb0a67a76.png)

**Comment by frankl1** [comment]
> could you post the whole shapelet log here please? I'll take a look then
[ED_Shapelets.xlsx](https://github.com/uea-machine-learning/tsml/files/3756238/ED_Shapelets.xlsx)

**Comment by frankl1** [comment]
> So I have just run chinatown and recreated the extracted shapelets. Two things: indexing is from zero, are you looking at the correct series, and are you using sktime not tsml? The shapelet you give above is from series 7 position 20
> ![image](https://user-images.githubusercontent.com/9594042/67203759-dd83ea80-f403-11e9-8d49-f5acb0a67a76.png)

I'm using tsml and the shapelet I gave above is from the series 17 starting at position 2 (here is the  [log](https://github.com/uea-machine-learning/tsml/files/3756238/ED_Shapelets.xlsx)).

I used tsml to extract shapelets, and use python notebook to process the output log. Here is my python [Notebook](https://github.com/frankl1/Uncertain-Shapelet-Transform/blob/master/Shapelet-analysis.ipynb).
