### ISSUE TITLE
timeseriesweka.utilities

### ISSUE THREAD

**Issue by TonyBagnall** [uea-machine-learning/tsml#18]
is all this necessary? James and Aaron are I think responsible for the bulk of this code. What uses it? Apart from the obvious, is most of it not needed or only used by shapelets? 
![image](https://user-images.githubusercontent.com/9594042/52332690-5ae10980-29f3-11e9-9d89-abe941673690.png)

**Comment by James-Large** [comment]
**Things that I know are needed:** 

- BitWord (required by boss, originally intended to use in other dictionary classifiers too but was dropped. can move to some boss-specific package)

**These can be moved to their own evaluation package**, as opposed to living in utils. This stuff has out-grown utils and become their own thing. ClassifierResultsCollection and MultipleClassifierResultsCollection could easily be merged, but that can be refactored later after the main purge/moving about. MultipleClassifierEvaluation could also be moved from development (or w/e its now called) to the same evaluation package as these. 
- ClassifierResults  
- ClassifierResultsAnalysis
- ClassifierResultsCollection
- MultipleClassifierResultsCollection 

**These are all fine in principle** and are broadly what the utilities package should be for. They need cleaning up documenting but the files in general should be left here
- InstanceTools 
- GenericTools 
- FileHandlingTools
- StatisticalUtilities
- ClassifierTools
- Utilities (should be renamed, or the functionality dispersed among the other 'tools' classes

50/50 On these: 
- CrossValidator: could go into the evaluation package too? or development/experiments
- ErrorReport: I think this is fine/should stay here, though no one else uses it
- FoldCreator: Useful in principle, and is the sort of thing I'd imagine should be in utilities, but other stuff supercedes it. either move all the other stuff to this or just delete this file. Findusages = 0 
- Timer: should really just use some library for this if we're going whole-hog. Was used in a few places just to time certain functions etc. Currently only used in one of the boss variants, fine either way if deleted
- DebugPrinting: used in a few classes, just nice for very lightweight optional printing. Again if we're going whole-hog, delete this and start using loggers properly

Try deleting/up to others:
- AttributeFilterBridge
- AttributeSelectionTools

And then the interfaces... dont know

**Comment by TonyBagnall** [comment]
an evaluation package is a very good idea, CrossValidator should go with them I think, given it, well evaluates. Can we refactor StatisticalUtilities to StatisticalTools? Also seems to be duplicated in Utilities. I think delay on the 50/50 stuff for now. So

**Comment by TonyBagnall** [comment]
So two actions to close this thread:

**Comment by TonyBagnall** [comment]
I think I have removed the attribute stuff. Three proposed actions to close this thread then.
1. James to sort out evaluation package and put it somewhere sensible.
2. StatisticalUtilities renamed tools for compliance.
3. George to strip anything he wants to keep in Utilities.java and put in StatisticalTools 
sound reasonable?

**Comment by goastler** [comment]
@TonyBagnall I can strip some stuff out but certain things I'd like to keep, however these are really statistical tools tbh. I can put them into a dedicated class, e.g. ArrayUtilities (as most of them are array operations, e.g. add, etc)

**Comment by TonyBagnall** [comment]
done some tidying but two questions
1) what is the difference between Tools and Utilities? File names are 50/50 
2) We should move the TrainAccuracyEstimate, but where to?

![image](https://user-images.githubusercontent.com/9594042/61828356-6075c300-ae5e-11e9-8063-bfdea75d4ff9.png)

**Comment by MatthewMiddlehurst** [comment]
Would probably be best to have an interfaces folder/package, there are other random ones floating around like the contract ones.

**Comment by TonyBagnall** [comment]
going to close this, ClassifierResults has been tidied up
