### ISSUE TITLE
Why z-normalization in shapelet comparison? 

### ISSUE THREAD

**Issue by vctrop** [uea-machine-learning/tsml#207]
Hello, dear researchers.

Your paper "Classification of time series by shapelet transformation" claims that all shapelets must be normalized prior to shapelet comparisons (to enable scale-independent comparison).

To my understanding, this could be achieved by dividing all shapelet values by the shapelet's euclidean norm, but instead you choose to use a more computationally expensive z-normalization. Is this choice arbitrary or am I missing something important here?

Thank you for your time.

**Comment by TonyBagnall** [comment]
I'm just tidying up, I'll close this issue. Thanks for the input. I have been meaning to measure the effect of normalisation on shapelets for some time. If we dont have to do it, evaluation can be made *much* faster. I'll also look at Euclidean norm
