### ISSUE TITLE
Measuring max memory during build process

### ISSUE THREAD

**Issue by TonyBagnall** [uea-machine-learning/tsml#211]
we need to figure out how to do this. Two approaches:
1) call external linux tools (George looking at this)
2) run classifier in its own thread, wait in main to get notified by the garbage collector as to the max memory used 
some ideas here
https://cruftex.net/2017/03/28/The-6-Memory-Metrics-You-Should-Track-in-Your-Java-Benchmarks.html#conclusion

**Comment by TonyBagnall** [comment]
this looks like a solution 
http://www.fasterj.com/articles/gcnotifs.shtml

**Comment by TonyBagnall** [comment]
MemoryMonitor is in the experiments package, I will leave this issue open until it is debugged and integrated into Experiments.java and ClassifierResults/Collate results

**Comment by TonyBagnall** [comment]
this needs integrating into Experiments and the results collater/MCE. @James-Large could you sort this please?

**Comment by James-Large** [comment]
Think I in general need to get up to speed with changes to codebase over last month or two. iirc there's maybe two different memory monitor things in the codebase atm? (was it a comment on slack/issue/pr somewhere?) etc.

Will add this to notes of things to do, but wont be immediate. Will have an informal meeting with people first to see what's what

**Comment by TonyBagnall** [comment]
Experiments is now externally monitoring the memory and writing it to file. MultipleClassifierEvaluation now collates this
