### ISSUE TITLE
implement .ts loader

### ISSUE THREAD

**Issue by TonyBagnall** [uea-machine-learning/tsml#212]
it would be good to be able to load files in .ts format (sktime format) into Instances

**Comment by ABostrom** [comment]
I might have a punt at this.

**Comment by TonyBagnall** [comment]
go for it! It would be helpful

**Comment by TonyBagnall** [comment]
@ABostrom did youd push this?

**Comment by ABostrom** [comment]
yeah its in a separate branch as i haven't fully tested it. 
https://github.com/uea-machine-learning/tsml/tree/TSFileReader
