### ISSUE TITLE
InstanceTools.removeRedundantTrainAttributes

### ISSUE THREAD

**Issue by TonyBagnall** [uea-machine-learning/tsml#219]
this does what it says on the tin, it removes attributes with just one value, but has two problems
1) it does a second weird test of adjacent values, think its meant
2) It would be good (I think) to also remove attributes with all the same values

![image](https://user-images.githubusercontent.com/9594042/68865096-1c971a00-06ea-11ea-8856-5fb998990dd2.png)

**Comment by ABostrom** [comment]
Could we have maybe a second function which is removeAllMatchingAttributes?

**Comment by TonyBagnall** [comment]
I think that would be helpful, especially for shapelets. We could also remove highly correlated attributes. ShapeletTransform is tricky. On the one hand, more shapelets in transform is generally better. On the other, more shapelets really impacts on classifier build time.

**Comment by ABostrom** [comment]
I think this is in part resolved by my new PR.

I might look at RemoveCorrelatedAttributes. What correlation metrics would we want?
- Pearson?
- Kendall?
- Spearman?

**Comment by TonyBagnall** [comment]
I think we will settle for this now, and enhance it when we encounter a need
