### ISSUE TITLE
.jar file link may be broken

### ISSUE THREAD

**Issue by Jason-Ludmir** [uea-machine-learning/tsml#301]
Using the link in Readme.rst: "download the [jar file](https://github.com/TonyBagnall/uea-tsc/TSCjar31_5_20.zip) and include as a dependency in your project," getting redirected to a "not found" page.

**Comment by TonyBagnall** [comment]
hi, I have put a jar file here of the latest code. http://timeseriesclassification.com/Downloads/tsml11_3_2020.jar
let me know if you have any problems, please feel free to raise issues, its really helpful.  I'll adjust the readme
