### ISSUE TITLE
getParas() and getParameters()

### ISSUE THREAD

**Issue by TonyBagnall** [uea-machine-learning/tsml#311]
getParas() is in ParameterSplittable, getParameters() is in EnhancedAbstractClassifier. Any reason to have both? 

![image](https://user-images.githubusercontent.com/9594042/76389685-ba7eb680-6363-11ea-8cf6-f4940e10b995.png)

**Comment by TonyBagnall** [comment]
in fact, do we still need parameterSplittable?

**Comment by TonyBagnall** [comment]
sorry, getParameters is in saveParameterInfo
![image](https://user-images.githubusercontent.com/9594042/76389776-fe71bb80-6363-11ea-838e-33912f97969b.png)

**Comment by TonyBagnall** [comment]
btw, I very much like James's habit of putting the interface name afte the @Override, please adopt this style

**Comment by James-Large** [comment]
ParameterSplittable (or potentially a rename to just Splittable/Threadable etc) as a general concept could still be useful for any jobs we may want to split across compute jobs, with the general idea being: 

Work is threadable (but in single job), or one step further this work is splittable across nodes and can be collated in a post processed fashion

So basically threadable -> triviallythreadable

Regardless, getParas in parameterSplittable can go in theory I think, in practice there may be some janky dependencies lying around.

Main thing that would be useful from there is public void setParametersFromIndex(int x);, or would be renamed something like setWorkIndex()

**Comment by TonyBagnall** [comment]
removed without any impact (he says ...)
