### ISSUE TITLE
WDTW early abandon problem with variable length series

### ISSUE THREAD

**Issue by HerrmannM** [uea-machine-learning/tsml#374]
Hi!

In wdtw (src/main/java/tsml/classifiers/distance_based/distances/wdtw/WDTWDistance.java) at line 95, the check abort with +INFINITY if the second series as a length of 1 as the code cannot enter the nested for loop.
Quick fix : use  if (overflow&&bLength>1)

Cheers,
Mat

**Comment by TonyBagnall** [comment]
cheers Mat, given this to @goastler, although would be happy to accept a PR :)

**Comment by HerrmannM** [comment]
PR done https://github.com/uea-machine-learning/tsml/pull/393 !
Cheers,
Mat

**Comment by TonyBagnall** [comment]
ta mat
