### ISSUE TITLE
Difference in Algorithms Results on TSC website

### ISSUE THREAD

**Issue by ThisIsNSH** [uea-machine-learning/tsml#378]
While using **/java/tsml/examples/ClassificationExamples.java class** to run all the classifiers, I found my results close but not the same as mentioned on the website. 

One significant discovery was that Published Results and Recreated Results had a very large difference on the website. For example, 

_**Published Result for [Fast Shapelets](http://www.timeseriesclassification.com/algorithmdescription.php?algorithm_id=107) on GunPoint = 0.061
Recreated Result for [Fast Shapelets](http://www.timeseriesclassification.com/algorithmdescription.php?algorithm_id=107) on GunPoint = 0.9296**_

**_Published Result for [Shapelet Transform](http://www.timeseriesclassification.com/algorithmdescription.php?algorithm_id=110) on GunPoint = 0.013
Recreated Result for [Shapelet Transform](http://www.timeseriesclassification.com/algorithmdescription.php?algorithm_id=110) on GunPoint = 0.9987_**

I am worried that I am misinterpreting the Published Results data on the website as accuracy. I went on studying other algorithms and found that Published results are 0.0XX for other algorithms too. 

Another discovery I made was the difference in Recreated Results and the Results I calculated. For example,  

**_Recreated Result for [COTE](http://www.timeseriesclassification.com/algorithmdescription.php?algorithm_id=113) on GunPoint = 0.9919
Reproduced Result for COTE on GunPoint (by me) = 0.98_**

**_Recreated Result for [LPS](http://www.timeseriesclassification.com/algorithmdescription.php?algorithm_id=115) on GunPoint = 0.9719
Reproduced Result for LPS on GunPoint (by me) = 1.0_**

I am unable to understand why I am not being able to get the results mentioned on the website. I am using MacBook Air with 8GB RAM & 1.8GHz Dual-core i5 processor.

**Comment by TonyBagnall** [comment]
hi, thanks for this. I've just looked and some of the ReportedResults are indeed errors not accuracies, I will refactor. 

I'll look at the recreation, but LPS is not a well maintained or much used classifier. On the above, which COTE classifier does it refer to?

**Comment by ThisIsNSH** [comment]
Hello 

Thanks for informing that the ReportedResults are errors and not accuracies. 

I ran Flat COTE classifier.

**Comment by ThisIsNSH** [comment]
@TonyBagnall 
To reproduce the result for Flat COTE, without any modification I ran the following code in ClassificationExamples.java

`public static void main(String[] args){`
`            String[] paras={"COTE","GunPoint","1","src/main/java/experiments/data/tsc/","C:/Temp/"};`
`            singleClassifierAndFold(paras);`
`}`

Do I have to change the fold to 100? Or run this function in a loop with fold 1-100 and then average the accuracies? 

Running DTD on GunPoint in 3 ways:

1. **Fold = 1**             _Accuracy = 0.9333333333333333_
2. **Fold = 100**        _Accuracy = 0.8866666666666667_
3. **Fold = 1-100 then averaged**              _Accuracy = 0.8832_ 

In all three ways, I could not match the accuracy presented on the website for **DTD = 0.9627**

**Comment by TonyBagnall** [comment]
hi, so the results may not match exactly with that classifier. At the time we wrote it, we were not fully seeding classifiers to get exact reproducability. Also, the underlying code used by FlatCOTE may have changed. All recent classifiers (e.g. HIVE-COTE, RISE, STC, TSF, cBOSS) are fully seeded and results are exactly reproducable

**Comment by ThisIsNSH** [comment]
Thanks a lot, @TonyBagnall for helping me with this issue. 

I ran TSF a couple of days back and achieved **0.96** but on the website, it is **0.9617**

I ran the code with **Fold = 1**. Do I need to run the classifier code 100 times for folds 1-100 and average their accuracies to get the same result on the website? 

Sorry to ask a lot of questions, I want to make sure that I am running the code in the right way.

**Comment by TonyBagnall** [comment]
Im not sure what results you are looking at, but I think 0.9617 is averaged over multiple folds. If you go here 
https://timeseriesclassification.com/results.php
there is a link to   https://timeseriesclassification.com/results/ResultsByClassifier/TSF_TestFolds.csv
 you will see there that the first resample for TSF on GunPoint is 0.96, so you are using it correctly.

**Comment by ThisIsNSH** [comment]
@TonyBagnall Thanks a lot for clarifying my doubt. 😊

**Comment by TonyBagnall** [comment]
no problem, I'll close the issue, feel free to raise another
