### ISSUE TITLE
Implement ROCKET

### ISSUE THREAD

**Issue by MatthewMiddlehurst** [uea-machine-learning/tsml#434]
An implementation of ROCKET as a transformer or classifier with multivariate capabilities is desirable.

Paper: https://link.springer.com/article/10.1007/s10618-020-00701-z

sktime transformer: https://github.com/alan-turing-institute/sktime/blob/master/sktime/transformers/series_as_features/rocket.py

**Comment by ABostrom** [comment]
Do we have an efficient way to perform convolutions in TSML at the moment?

I could write a function to extract/calculate convolutions, which would get us part of the way there.

**Comment by ABostrom** [comment]
Implementing Convolutiosn for this :

single pad value. (0,1, mean, mirror)

**Comment by TonyBagnall** [comment]
I think this is done now @MatthewMiddlehurst ? Can you close this if it has been done
