### ISSUE TITLE
examples.DataHandling

### ISSUE THREAD

**Issue by TonyBagnall** [uea-machine-learning/tsml#482]
the DataHandling examples could be updated to include the new data representation. @c-eg perhaps?

**Comment by c-eg** [comment]
Yeah sure

**Comment by c-eg** [comment]
@TonyBagnall There appears to be an issue with uploading .ts files as Intellij sees it as a TypeScript file. Maybe this would be a good time to sort the file extension naming?

**Comment by TonyBagnall** [comment]
hi conor, uploading in what sense? They should be loadable into memory with DatsetLoading. We could change the extension, but there is a lot of refactoring to do in both toolkits if we do, and I dont think it is the time.

**Comment by c-eg** [comment]
I wanted to upload the ItalyPowerDemand train and test .ts files to the data folder (tsml\src\main\java\experiments\data\tsc\ItalyPowerDemand). 
Yes they will be but I'm pretty sure it will fail the TravisCI build check because it sees the file as a TypeScript file.

**Comment by TonyBagnall** [comment]
ah right I see! Test it out

**Comment by TonyBagnall** [comment]
worked on sktime, should be ok 
![image](https://user-images.githubusercontent.com/9594042/109689418-2d88ca80-7b7d-11eb-9b6d-a7e8d16f65ad.png)

**Comment by c-eg** [comment]
Okay great, thank you.
