### ISSUE TITLE
readme on front page needs updating

### ISSUE THREAD

**Issue by TonyBagnall** [uea-machine-learning/tsml#515]
it needs to include more recent classifier additions.

**Comment by divyodatasci** [comment]
I would like to work on this.

**Comment by TonyBagnall** [comment]
great, although I think @MatthewMiddlehurst may have updated it already?

**Comment by divyodatasci** [comment]
okay, I will look for something else to work on.

**Comment by TonyBagnall** [comment]
thanks, your contribution would be most welcome, I'll take a look for a good first issue
