### ISSUE TITLE
may you help to get 26 equal length datasets HIVE-COTE 2.0: a new meta ensemble for time series classification

### ISSUE THREAD

**Issue by Sandy4321** [uea-machine-learning/tsml#545]
may you help to get 26 equal length datasets HIVE-COTE 2.0: a new meta ensemble for time series classification
as written in https://arxiv.org/pdf/2104.07551.pdf
. For our multivariate experiments we use all 26 equal length datasets of the 30
total from the UEA multivariate time series archive (Bagnall et al., 2018).

**Comment by MatthewMiddlehurst** [comment]
http://www.timeseriesclassification.com/dataset.php 

They should all be available for download at the above website. Let us know if any are missing.

**Comment by Sandy4321** [comment]
great 
which data sets exactly you used 
do you have code to download/use  them automatically

**Comment by MatthewMiddlehurst** [comment]
"ArticularyWordRecognition"
    "AtrialFibrillation"
    "BasicMotions"
    "Cricket"
    "DuckDuckGeese"
    "EigenWorms"
    "Epilepsy"
    "EthanolConcentration"
    "ERing"
    "FaceDetection"
    "FingerMovements"
    "HandMovementDirection"
    "Handwriting"
    "Heartbeat"
    "Libras"
    "LSST"
    "MotorImagery"
    "NATOPS"
    "PenDigits"
    "PEMS-SF"
    "PhonemeSpectra"
    "RacketSports"
    "SelfRegulationSCP1"
    "SelfRegulationSCP2"
    "StandWalkJump"
    "UWaveGestureLibrary"
    
There are some data loading utilities in aeon, some examples here https://github.com/aeon-toolkit/aeon/tree/main/examples/datasets

**Comment by Sandy4321** [comment]
great it works
by the way , do you have capability to predict for mixture of continuous and categorical features 

it is code I used
from aeon.datasets import load_classification


my_files =  ["ArticularyWordRecognition", 
"AtrialFibrillation", 
"BasicMotions", 
"Cricket", 
"DuckDuckGeese", 
"EigenWorms", 
"Epilepsy", 
"EthanolConcentration", 
"ERing", 
"FaceDetection", 
"FingerMovements", 
"HandMovementDirection", 
"Handwriting", 
"Heartbeat", 
"Libras", 
"LSST", 
"MotorImagery", 
"NATOPS", 
"PenDigits", 
"PEMS-SF", 
"PhonemeSpectra", 
"RacketSports", 
"SelfRegulationSCP1", 
"SelfRegulationSCP2", 
"StandWalkJump", 
"UWaveGestureLibrary"]

# This will not download, because Arrowhead is already in the directory.
# Change the extract path or name to downloads
for each_file in  my_files:
    print('\nstart', each_file)
    #X, y, meta_data = load_classification("ArrowHead")
    X, y, meta_data = load_classification(each_file)
    print(" Shape of X = ", X.shape)
    print(" Meta data = ", meta_data)
    print('done ', each_file)
q = 0
