### ISSUE TITLE
Java version/netbeans

### ISSUE THREAD

**Issue by TonyBagnall** [uea-machine-learning/tsml#65]
A discussion point/issue arising from Travis. Should we switch to IntelliJ and update from Java 8? Open question we have gone over, but I'll leave it here

**Comment by goastler** [comment]
Have fixed the issue in PR #66 with setting java version to openjdk-8. Must switch back to use jdk 11 or newer once we've updated weka

**Comment by TonyBagnall** [comment]
bumping this after recent intellij discussion

**Comment by TonyBagnall** [comment]
everyone moved/moving to intellij, closing
