### ISSUE TITLE
Filters

### ISSUE THREAD

**Issue by TonyBagnall** [uea-machine-learning/tsml#97]
the long term question is, do we want to continue using the Filter mechanism in weka for transformers. 
Pros for Filter:
1. Fits into weka way
2. Its how we have done them all
Cons
1. Stupid BatchFilter usage pattern
2. I prefer the name Transformer to Filter and sktime uses Transformer

any other thoughts? Whatever we do, they all need capabilities checking

**Comment by ABostrom** [comment]
We don't really use filters in the weka way. 

You're supposed to call Filter.use(the filter);

I think transformer is clearer and states our goal. It aligns with sktime so less prerequisite knowledge to switch between. Is more inline with sklearn too. 

Scrap filter, move to transformer has my vote.

**Comment by TonyBagnall** [comment]
I also dont like the bloated Filter inheritance hierarchy. 

We would then need a Transformer interface, and I dont think fit/predict is right. buildTransformer and transform? 

this aint happening soon. Perhaps coordinate it with the new TimeSeriesInstances

**Comment by TonyBagnall** [comment]
so from discussion this morning, favoured option is to extend Filter (or some subclass of Filter) into AbstractTransformer with abstract methods
fit(Instances)
transform(Instances)
fitTransform(Instances)
transform(Instance)
and attributes
Instances header
that way we can override outputFormat etc and everything should be backward compatible

**Comment by TonyBagnall** [comment]
or buildsTransformer not fit may be more weka compatible

**Comment by TonyBagnall** [comment]
I have pushed a Transformer interface and ShapeletTransform is the first to go over
